### ISSUE TITLE
How to set my servers URLs?

### ISSUE THREAD

**Issue by fguillen** [film42/redis-cluster-activesupport#1]
Maybe is too obvious that is not necessary to mention but I don't find how I have to set my Redis Servers URLs?

    CampaignPlatform::Application.config.cache_store = :redis_cluster_store, ["redis://server1:6379/0/", "redis://server2:6379/0/"]

    CampaignPlatform::Application.config.cache_store = :redis_cluster_store, :servers => ["redis://server1:6379/0/", "redis://server2:6379/0/"]

?

**Comment by film42** [comment]
Hey @fguillen ! This gem requires you to use a redis cluster proxy like corvus. It is not a redis cluster client. Because a cluster proxy might raise redis command errors to signal an outage or something, this gem allows you to handle those specific errors. By default this works with corvus since that's what I work with in production, but you can add as many custom errors as you'd like.

Since this is just an extension, you can read documentation for configuring everything at the https://github.com/redis-store/redis-rails project.

**Comment by fguillen** [comment]
@film42 thanks, understood!
